name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter Framework
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Grant Execute Permission for Gradlew
        run: chmod +x android/gradlew
        continue-on-error: true

      - name: Fetch Flutter Packages
        run: |
          flutter pub get

      - name: Build APK File
        run: |
          flutter build apk --release --no-tree-shake-icons

      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: vmware-android-app-release
          path: build/app/outputs/flutter-apk/app-release.apk
          
